# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: DappyDig's Blog
email: mr [dot] a [dot] tripathi [at] gmail
description: >- # this means to ignore newlines until "baseurl:"
  DappyDig's Blog about Cloud, Distributed Computing, General problems of an Embedded Systems Engineer in the world of Cloud. 
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://kryochronic.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: dappyd1g
github_username:  kryochronic

# Build settings
theme: minima
plugins:
  - jekyll-feed
  # - jekyll-plantuml
  - "kramdown-plantuml"
  - jemoji

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
# #
# exclude:
#   - bin/
  # - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/


# plantuml:
#   # background_color: #
#   # tmp_folder:
#   # dot_exe:

#   # plantuml_jar: 'bin/plantuml-1.2022.0.jar' 
#   tmp_folder: '_posts/puml_imgs/'
#   # type:         'svg'
#   # ssl_noverify: '0'
#   # http_debug:   '0'


kramdown:
  plantuml:
    theme:
      name: spacelab